import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design token system
        surface: "#1d0f12",
        "surface-dim": "#1d0f12",
        "surface-bright": "#463537",
        "surface-container-lowest": "#180a0d",
        "surface-container-low": "#26181a",
        "surface-container": "#2b1c1e",
        "surface-container-high": "#362628",
        "surface-container-highest": "#413033",
        "on-surface": "#f7dcdf",
        "on-surface-variant": "#e1bec2",
        "inverse-surface": "#f7dcdf",
        "inverse-on-surface": "#3d2c2f",
        outline: "#a9898d",
        "outline-variant": "#5a4044",
        "surface-tint": "#ffb2be",
        primary: "#ffb2be",
        "on-primary": "#660026",
        "primary-container": "#ff4d7e",
        "on-primary-container": "#5a0021",
        "primary-fixed": "#ffd9de",
        "primary-fixed-dim": "#ffb2be",
        "on-primary-fixed": "#3f0015",
        "on-primary-fixed-variant": "#900039",
        "inverse-primary": "#b90f4e",
        secondary: "#cdbfee",
        "on-secondary": "#342a50",
        "secondary-container": "#4e436a",
        "on-secondary-container": "#bfb1e0",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#cdbfee",
        "on-secondary-fixed": "#1f153a",
        "on-secondary-fixed-variant": "#4b4168",
        tertiary: "#59e073",
        "on-tertiary": "#003911",
        "tertiary-container": "#01a742",
        "on-tertiary-container": "#00320e",
        "tertiary-fixed": "#77fd8c",
        "tertiary-fixed-dim": "#59e073",
        "on-tertiary-fixed": "#002107",
        "on-tertiary-fixed-variant": "#00531d",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "#413033",
        background: "#1d0f12",
        "on-background": "#f7dcdf",
      },
      fontFamily: {
        sans: ["Noto Sans SC", "system-ui", "sans-serif"],
        serif: ["Noto Serif SC", "Georgia", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "300" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "500" }],
        "display-hero": ["96px", { lineHeight: "100px", letterSpacing: "-0.02em", fontWeight: "200" }],
        "display-hero-mobile": ["80px", { lineHeight: "84px", fontWeight: "200" }],
        "body-quote": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "300" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "390px",
        "edge-margin": "24px",
        "section-gap": "48px",
        "stack-gap": "16px",
      },
      animation: {
        "drift-up": "driftUp 0.8s ease-out forwards",
        "fade-up": "fadeInUp 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "heart-pulse": "heartPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        scanning: "scanning 4s linear infinite",
        flicker: "flicker 2s infinite",
      },
      keyframes: {
        driftUp: {
          from: { transform: "translateY(12px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        heartPulse: {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { opacity: "0.5" },
          "100%": { transform: "scale(1.3)", opacity: "0" },
        },
        scanning: {
          "0%": { top: "10%", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { top: "90%", opacity: "0" },
        },
        flicker: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
          "75%": { opacity: "0.9" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
